name: video_preview_thumbnails
description: "Video preview thumbnails base vtt file"
version: 0.0.1
homepage: https://github.com/mbfakourii/video_preview_thumbnails
repository: https://github.com/mbfakourii/video_preview_thumbnails
issue_tracker: https://github.com/mbfakourii/video_preview_thumbnails/issues

topics:
  - vtt
  - video-preview-thumbnails
  - sprites
  - preview
  - thumbnail

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  # Dio
  dio: ^5.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

screenshots:
  - description: Video preview thumbnails logo.
    path: screenshots/logo.png